const bulkPrices=[{min:10,price:7},{min:50,price:5},{min:100,price:4.5},{min:200,price:4},{min:250,price:3.8},{min:500,price:3.5}];
const lyca={id:1,brand:'Lyca Mobile',name:'Triple-SIM',type:'Prepaid',network:'Lyca Mobile',data:'3-in-1',speed:'LTE/5G*',price:7,code:'LY',image:'assets/sim/f932503a-66a1-4252-acf7-579a10b724ee.jpeg',esim:false};
const state={items:[],network:'Alle',brand:'Alle'};const $=s=>document.querySelector(s);const euro=n=>n.toLocaleString('de-DE',{style:'currency',currency:'EUR'});
function unitPrice(q){let p=7;for(const tier of bulkPrices)if(q>=tier.min)p=tier.price;return p}
function renderProducts(){const p=lyca;$('#products').innerHTML=`<article class="product"><div class="product-image"><img src="${p.image}" alt="Lyca Mobile Triple-SIM" loading="lazy"></div><div class="product-body"><span class="tag">Prepaid · Triple-SIM</span><div class="provider">LYCA MOBILE · DEUTSCHE NUMMER</div><h3>Lyca Mobile Triple-SIM</h3><p style="color:#aeb7c4">Bereits aktiviert · Mindestaufladung 5 € · Standard, Micro und Nano</p><div class="product-bottom"><div class="price"><strong>ab ${euro(3.5)}</strong><small>pro Stück bei 500 Stück</small></div><button class="add" data-add="1">Ab 10 Stück</button></div></div></article>`;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>window.addLycaProduct(10))}
function add(id,qty=1){const found=state.items.find(x=>x.id===id);if(found)found.qty+=qty;else state.items.push({...lyca,qty});renderCart();openCart()}
function renderCart(){const count=state.items.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=count;$('#cartItems').innerHTML=state.items.length?state.items.map(x=>{const unit=unitPrice(x.qty);return `<div class="cart-row"><div><strong>${x.brand}</strong><br><small>${x.name} · ${x.qty} Stück</small></div><div><strong>${euro(unit*x.qty)}</strong><br><small>${euro(unit)} / Stück</small></div></div>`}).join(''):'<div class="empty">Dein Warenkorb ist leer.</div>';$('#cartTotal').textContent=euro(state.items.reduce((s,x)=>s+unitPrice(x.qty)*x.qty,0))}
function openCart(){$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false');$('#backdrop').classList.add('show')}
function closeAll(){$('#cartDrawer').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true');$('#backdrop').classList.remove('show');$('#checkoutModal').classList.remove('show')}
window.addLycaProduct=qty=>add(1,qty);$('#cartOpen').onclick=openCart;$('#cartClose').onclick=closeAll;$('#backdrop').onclick=closeAll;$('#checkout').onclick=()=>{if(!state.items.length)return alert('Bitte zuerst die SIM-Karte in den Warenkorb legen.');$('#checkoutModal').classList.add('show');$('#backdrop').classList.remove('show')};$('#checkoutClose').onclick=()=>$('#checkoutModal').classList.remove('show');
$('#checkoutForm').onsubmit=async e=>{e.preventDefault();if(!state.items.length)return;const data=new FormData(e.target);const qty=state.items.reduce((s,x)=>s+x.qty,0);const payload={customer:{name:[data.get('firstName'),data.get('lastName')].filter(Boolean).join(' '),email:data.get('email'),address:data.get('address')},items:[{id:'1',qty}]};const btn=e.target.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='CRYPTOMUS CHECKOUT …';try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Checkout konnte nicht gestartet werden.');window.location.href=d.checkout_url}catch(err){alert(err.message)}finally{btn.disabled=false;btn.textContent='Weiter zu Cryptomus'}};
const form=$('#checkoutForm');if(form){const currency=document.createElement('label');currency.className='full';currency.innerHTML='<span>Zahlungswährung</span><select name="currency"><option>BTC</option><option>USDT</option><option>ETH</option><option>TRX</option><option>BNB</option></select>';form.querySelector('.form-grid')?.appendChild(currency)}
renderProducts();renderCart();
