const bulkPrices=[{min:10,price:7},{min:50,price:5},{min:100,price:4.5},{min:200,price:4},{min:250,price:3.8},{min:500,price:3.5}];
const lyca={id:1,brand:'Lyca Mobile',name:'Triple-SIM',type:'Prepaid',network:'Lyca Mobile',data:'3-in-1',speed:'LTE/5G*',price:7,code:'LY',image:'assets/sim/f932503a-66a1-4252-acf7-579a10b724ee.jpeg',esim:false};
const state={items:[],network:'Alle',brand:'Alle'};const $=s=>document.querySelector(s);const euro=n=>n.toLocaleString('de-DE',{style:'currency',currency:'EUR'});
function unitPrice(q){let p=7;for(const tier of bulkPrices)if(q>=tier.min)p=tier.price;return p}
function renderProducts(){const p=lyca;$('#products').innerHTML=`<article class="product"><div class="product-image"><img src="${p.image}" alt="Lyca Mobile Triple-SIM" loading="lazy"></div><div class="product-body"><span class="tag">Prepaid · Triple-SIM</span><div class="provider">LYCA MOBILE · DEUTSCHE NUMMER</div><h3>Lyca Mobile Triple-SIM</h3><p style="color:#aeb7c4">Bereits aktiviert · Mindestaufladung 5 € · Standard, Micro und Nano</p><div class="product-bottom"><div class="price"><strong>ab ${euro(3.5)}</strong><small>pro Stück bei 500 Stück</small></div><button class="add" data-add="1">Ab 10 Stück</button></div></div></article>`;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>window.addLycaProduct(10))}
function add(id,qty=1){const found=state.items.find(x=>x.id===id);if(found)found.qty+=qty;else state.items.push({...lyca,qty});renderCart();openCart()}
function renderCart(){const count=state.items.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=count;$('#cartItems').innerHTML=state.items.length?state.items.map(x=>{const unit=unitPrice(x.qty);return `<div class="cart-row"><div><strong>${x.brand}</strong><br><small>${x.name} · ${x.qty} Stück</small></div><div><strong>${euro(unit*x.qty)}</strong><br><small>${euro(unit)} / Stück</small></div></div>`}).join(''):'<div class="empty">Dein Warenkorb ist leer.</div>';$('#cartTotal').textContent=euro(state.items.reduce((s,x)=>s+unitPrice(x.qty)*x.qty,0))}
function openCart(){$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false');$('#backdrop').classList.add('show')}
function closeAll(){$('#cartDrawer').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true');$('#backdrop').classList.remove('show');$('#checkoutModal').classList.remove('show')}
window.addLycaProduct=qty=>add(1,qty);$('#cartOpen').onclick=openCart;$('#cartClose').onclick=closeAll;$('#backdrop').onclick=closeAll;$('#checkout').onclick=()=>{if(!state.items.length)return alert('Bitte zuerst die SIM-Karte in den Warenkorb legen.');$('#checkoutModal').classList.add('show');$('#backdrop').classList.remove('show')};$('#checkoutClose').onclick=()=>$('#checkoutModal').classList.remove('show');
$('#checkoutForm').onsubmit=async e=>{e.preventDefault();if(!state.items.length)return;const form=new FormData(e.target);const customer={name:`${form.get('firstName')} ${form.get('lastName')}`.trim(),email:String(form.get('email')||'').trim(),address:String(form.get('address')||'').trim()};const items=state.items.map(x=>({name:`${x.brand} ${x.name}`,qty:x.qty,price:unitPrice(x.qty)}));const btn=e.target.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='BESTELLUNG WIRD VORBEREITET …';try{const r=await fetch('/api/telegram-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,items,payment_status:'UNBEZAHLT'})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Bestellung konnte nicht vorbereitet werden.');$('#success').hidden=false;$('#success').textContent=`✓ Bestellung ${data.order_number} erstellt. Telegram Support wird geöffnet …`;e.target.reset();const supportUrl=data.support_url||data.telegram_url||'https://t.me/Lyca_Support';setTimeout(()=>{window.location.href=supportUrl},250)}catch(err){alert(err.message)}finally{btn.disabled=false;btn.textContent='Weiter zu Telegram'}};
renderProducts();renderCart();
