const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const telegram=require('./telegram-bot');
const port=Number(process.env.PORT)||10000;const root=__dirname;const CANONICAL_HOST='aktiv-lyca.de';const SUPPORT_USERNAME='Lyca_Support';const SUPPORT_URL='https://t.me/Lyca_Support';const mimeTypes={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon'};
function safePath(urlPath){const decoded=decodeURIComponent(urlPath.split('?')[0]);const relative=decoded==='/'?'index.html':decoded.replace(/^\/+/, '');const filePath=path.resolve(root,relative);return filePath.startsWith(root+path.sep)||filePath===root?filePath:null}
function parseJson(req){return new Promise((resolve,reject)=>{let body='';req.on('data',chunk=>{body+=chunk;if(body.length>1000000)req.destroy(new Error('Payload too large'))});req.on('end',()=>{try{resolve(JSON.parse(body||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
function sendJson(res,status,payload){const data=JSON.stringify(payload);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(data)}
function makeOrderNumber(){const d=new Date();const stamp=d.toISOString().slice(0,10).replace(/-/g,'');const rnd=crypto.randomBytes(3).toString('hex').toUpperCase();return `LYCA-${stamp}-${rnd}`}
function makeInvoiceNumber(orderNumber){return orderNumber.replace(/^LYCA-/,'LYCA-RE-')}
async function telegramOrder(req,res){try{const data=await parseJson(req);const customer=data.customer||{};const items=Array.isArray(data.items)?data.items:[];if(!customer.name||!customer.email||!customer.email.includes('@')||!customer.address||!items.length)return sendJson(res,400,{error:'Bitte Name, E-Mail, Anschrift und Warenkorb angeben.'});const orderNumber=makeOrderNumber();const invoiceNumber=makeInvoiceNumber(orderNumber);const normalizedItems=items.map(x=>({name:String(x.name||'Lyca Mobile Triple-SIM'),qty:Math.max(1,Number(x.qty)||1),price:Math.max(0,Number(x.price)||0)}));const total=normalizedItems.reduce((sum,x)=>sum+x.price*x.qty,0);const order={orderNumber,invoiceNumber,createdAt:new Date().toLocaleString('de-DE',{timeZone:'Europe/Berlin'}),customer:{name:String(customer.name).trim(),email:String(customer.email).trim(),address:String(customer.address).trim()},items:normalizedItems,total,paymentStatus:'UNBEZAHLT'};const result=telegram.sendOrder(order);sendJson(res,201,{ok:true,order_number:orderNumber,invoice_number:invoiceNumber,payment_status:order.paymentStatus,bot_username:telegram.username,bot_mode:'tokenless',bot_message:result.message,support_username:SUPPORT_USERNAME,support_url:SUPPORT_URL,telegram_url:SUPPORT_URL})}catch(err){console.error('Lyca order error:',err);sendJson(res,500,{error:err.message||'Bestellung konnte nicht verarbeitet werden.'})}}
function telegramStatus(req,res){sendJson(res,200,{ok:true,telegram_enabled:false,bot_enabled:true,bot_username:telegram.username,bot_mode:'tokenless',support_username:SUPPORT_USERNAME,support_url:SUPPORT_URL,chat_id_registered:false,message:'Bestellungen werden vorbereitet und anschließend der Telegram-Supportchat @Lyca_Support geöffnet. Eine echte Telegram-Bot-API-Weiterleitung benötigt weiterhin einen Bot-Token.'})}
async function lycaBot(req,res){try{if(req.method==='GET'){const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);const order=url.searchParams.get('order');return sendJson(res,200,{ok:true,bot:telegram.username,mode:'tokenless',support_username:SUPPORT_USERNAME,support_url:SUPPORT_URL,message:order?telegram.command(`/order ${order}`):telegram.command('/start'),orders:telegram.getOrders()})}const data=await parseJson(req);return sendJson(res,200,{ok:true,bot:telegram.username,mode:'tokenless',support_username:SUPPORT_USERNAME,support_url:SUPPORT_URL,message:telegram.command(data.command||data.text||'/help')})}catch(err){return sendJson(res,400,{ok:false,error:err.message})}}
const server=http.createServer(async(req,res)=>{if(req.method==='GET'&&req.url.split('?')[0]==='/api/telegram-status')return telegramStatus(req,res);if((req.method==='GET'||req.method==='POST')&&req.url.split('?')[0]==='/api/lyca-bot')return lycaBot(req,res);if(req.method==='POST'&&req.url.split('?')[0]==='/api/telegram-order')return telegramOrder(req,res);let filePath;try{filePath=safePath(req.url||'/')}catch{res.writeHead(400);return res.end('Bad Request')}if(!filePath){res.writeHead(403);return res.end('Forbidden')}fs.stat(filePath,(statErr,stat)=>{if(!statErr&&stat.isFile())return sendFile(filePath,res);sendFile(path.join(root,'index.html'),res)})});
function sendFile(filePath,res){fs.readFile(filePath,(err,data)=>{if(err){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Not Found')}const ext=path.extname(filePath).toLowerCase();res.writeHead(200,{'Content-Type':mimeTypes[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600'});res.end(data)})}server.listen(port,'0.0.0.0',()=>console.log(`Lyca Webshop server listening on port ${port}`));
