const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const telegram=require('./telegram-bot');
const port=Number(process.env.PORT)||10000;const root=__dirname;const CANONICAL_HOST='aktiv-lyca.de';const mimeTypes={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon'};
function safePath(urlPath){const decoded=decodeURIComponent(urlPath.split('?')[0]);const relative=decoded==='/'?'index.html':decoded.replace(/^\/+/, '');const filePath=path.resolve(root,relative);return filePath.startsWith(root+path.sep)||filePath===root?filePath:null}
function parseJson(req){return new Promise((resolve,reject)=>{let body='';req.on('data',chunk=>{body+=chunk;if(body.length>1000000)req.destroy(new Error('Payload too large'))});req.on('end',()=>{try{resolve(JSON.parse(body||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
function sendJson(res,status,payload){const data=JSON.stringify(payload);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(data)}
function makeOrderNumber(){const d=new Date();const stamp=d.toISOString().slice(0,10).replace(/-/g,'');const rnd=crypto.randomBytes(3).toString('hex').toUpperCase();return `LUCA-${stamp}-${rnd}`}
function makeInvoiceNumber(orderNumber){return orderNumber.replace(/^LUCA-/,'LUCA-RE-')}
async function telegramOrder(req,res){try{const data=await parseJson(req);const customer=data.customer||{};const items=Array.isArray(data.items)?data.items:[];if(!customer.name||!customer.email||!customer.email.includes('@')||!customer.address||!items.length)return sendJson(res,400,{error:'Bitte Name, E-Mail, Anschrift und Warenkorb angeben.'});const orderNumber=makeOrderNumber();const invoiceNumber=makeInvoiceNumber(orderNumber);const normalizedItems=items.map(x=>({name:String(x.name||'Lyca Mobile Triple-SIM'),qty:Math.max(1,Number(x.qty)||1),price:Math.max(0,Number(x.price)||0)}));const total=normalizedItems.reduce((sum,x)=>sum+x.price*x.qty,0);const order={orderNumber,invoiceNumber,createdAt:new Date().toLocaleString('de-DE',{timeZone:'Europe/Berlin'}),customer:{name:String(customer.name).trim(),email:String(customer.email).trim(),address:String(customer.address).trim()},items:normalizedItems,total,paymentStatus:'UNBEZAHLT'};if(!telegram.enabled)return sendJson(res,503,{error:'Luca-Telegram-Bot ist nicht aktiviert. LUCA_TELEGRAM_BOT_TOKEN muss in Render gesetzt sein.'});await telegram.sendOrder(order);sendJson(res,201,{ok:true,order_number:orderNumber,invoice_number:invoiceNumber,payment_status:order.paymentStatus,telegram_url:`https://t.me/${telegram.username}?start=${encodeURIComponent(orderNumber)}`})}catch(err){console.error('Luca Telegram order error:',err);sendJson(res,500,{error:err.message||'Bestellung konnte nicht an Telegram gesendet werden.'})}}
function telegramStatus(req,res){sendJson(res,200,{ok:true,telegram_enabled:telegram.enabled,bot_username:telegram.username||'Luca_Webshop_Bot',chat_id_registered:Boolean(telegram.getAdminChatId()),message:telegram.getAdminChatId()?'Luca Telegram ist für Bestellungen konfiguriert.':'LUCA_TELEGRAM_ADMIN_CHAT_ID ist noch nicht gesetzt.'})}
const server=http.createServer(async(req,res)=>{const host=(req.headers.host||'').split(':')[0].toLowerCase();if(req.method==='GET'&&req.url.split('?')[0]==='/api/telegram-status')return telegramStatus(req,res);if(req.method==='POST'&&req.url.split('?')[0]==='/api/telegram-order')return telegramOrder(req,res);let filePath;try{filePath=safePath(req.url||'/')}catch{res.writeHead(400);return res.end('Bad Request')}if(!filePath){res.writeHead(403);return res.end('Forbidden')}fs.stat(filePath,(statErr,stat)=>{if(!statErr&&stat.isFile())return sendFile(filePath,res);sendFile(path.join(root,'index.html'),res)})});
function sendFile(filePath,res){fs.readFile(filePath,(err,data)=>{if(err){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Not Found')}const ext=path.extname(filePath).toLowerCase();res.writeHead(200,{'Content-Type':mimeTypes[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600'});res.end(data)})}server.listen(port,'0.0.0.0',()=>console.log(`Luca Webshop server listening on port ${port}`));
