const token=process.env.TELEGRAM_BOT_TOKEN;
const adminChatId=process.env.TELEGRAM_ADMIN_CHAT_ID;
if(!token){console.log('Telegram bot disabled: TELEGRAM_BOT_TOKEN is not configured.');module.exports={enabled:false};return;}
const api=`https://api.telegram.org/bot${token}`;let offset=0;
async function tg(method,body){const r=await fetch(`${api}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json()}
async function send(chatId,text,extra={}){return tg('sendMessage',{chat_id:chatId,text,...extra})}
async function loop(){try{const data=await tg('getUpdates',{offset,timeout:25,allowed_updates:['message','callback_query']});for(const u of (data.result||[])){offset=u.update_id+1;await handle(u)}}catch(e){console.error('Telegram bot error:',e.message)}setTimeout(loop,1000)}
async function handle(u){const m=u.message;if(!m)return;const chatId=m.chat.id;const text=(m.text||'').trim();if(text==='/start'||text==='/help'){return send(chatId,'Lyca Mobile Bestellbot\n\nBestellungen für Triple-SIM über Telegram.\n\nMenge: 10 / 50 / 100 / 200 / 250 / 500 Stück\nZahlung: BTC / SOL / BNB\n\nNutze /order für eine Bestellung.')}if(text==='/order'){return send(chatId,'Welche Menge möchtest du bestellen?',{reply_markup:{inline_keyboard:[[{text:'10 Stück',callback_data:'qty:10'},{text:'50 Stück',callback_data:'qty:50'}],[{text:'100 Stück',callback_data:'qty:100'},{text:'200 Stück',callback_data:'qty:200'}],[{text:'250 Stück',callback_data:'qty:250'},{text:'500 Stück',callback_data:'qty:500'}]]}})}if(u.callback_query){const q=u.callback_query;await tg('answerCallbackQuery',{callback_query_id:q.id});if(q.data.startsWith('qty:')){const qty=Number(q.data.split(':')[1]);return send(q.message.chat.id,`Menge: ${qty} Stück\n\nWähle die Zahlungswährung:`,{reply_markup:{inline_keyboard:[[{text:'₿ Bitcoin (BTC)',callback_data:`pay:${qty}:BTC`},{text:'◎ Solana (SOL)',callback_data:`pay:${qty}:SOL`}],[{text:'◆ BNB',callback_data:`pay:${qty}:BNB`}]]}})}if(q.data.startsWith('pay:')){const [,qty,currency]=q.data.split(':');const order=`Neue Telegram-Bestellanfrage\n\nKunde: @${q.from.username||'ohne_username'}\nTelegram-ID: ${q.from.id}\nMenge: ${qty} Stück\nWährung: ${currency}`;if(adminChatId)await send(adminChatId,order);return send(q.message.chat.id,`Bestellung erfasst.\n\n${qty} Stück · ${currency}\n\nDer Support bestätigt jetzt den Endbetrag und die passende Zahlungsadresse. Bitte keine Zahlung senden, bevor die Adresse und das Netzwerk bestätigt wurden.`)}}}
loop();module.exports={enabled:true};
