const token=process.env.LUCA_TELEGRAM_BOT_TOKEN;
const configuredAdminChatId=process.env.LUCA_TELEGRAM_ADMIN_CHAT_ID||null;
let adminChatId=configuredAdminChatId;
let offset=0;
let started=false;
const botUsername=(process.env.LUCA_TELEGRAM_BOT_USERNAME||'Luca_Webshop_Bot').replace(/^@/,'');
const api=token?`https://api.telegram.org/bot${token}`:null;
const orders=new Map();
const wallets={BTC:'bc1qg808ntjfxgvnguepngpl6f7ddwana39z7m2qxx',SOL:'2uqEwjquFWXbJhuhSwkMtbGcm2mZbi4JBoJWd6jrzeJA',BNB:'0x7f6dde8179319425917eD0c9fd84952f98b0C2A4'};
async function tg(method,body={}){if(!api)throw new Error('LUCA_TELEGRAM_BOT_TOKEN missing');const r=await fetch(`${api}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.description||`Telegram API error (${r.status})`);return j.result}
async function send(chatId,text,extra={}){return tg('sendMessage',{chat_id:chatId,text,...extra})}
async function getBalances(){const out={BTC:'n/a',SOL:'n/a',BNB:'n/a'};try{const r=await fetch(`https://mempool.space/api/address/${wallets.BTC}`,{signal:AbortSignal.timeout(10000)});if(r.ok){const j=await r.json();const sats=(j.chain_stats?.funded_txo_sum||0)-(j.chain_stats?.spent_txo_sum||0);out.BTC=(sats/1e8).toFixed(8)+' BTC'}}catch{}try{const r=await fetch('https://api.mainnet-beta.solana.com',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'getBalance',params:[wallets.SOL]}),signal:AbortSignal.timeout(10000)});if(r.ok){const j=await r.json();out.SOL=((j.result?.value||0)/1e9).toFixed(6)+' SOL'}}catch{}try{const r=await fetch('https://bsc-dataseed.binance.org/',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_getBalance',params:[wallets.BNB,'latest']}),signal:AbortSignal.timeout(10000)});if(r.ok){const j=await r.json();out.BNB=(Number(BigInt(j.result||'0x0'))/1e18).toFixed(6)+' BNB'}}catch{}return out}
function isAdmin(chatId){return !!adminChatId&&String(chatId)===String(adminChatId)}
function formatOrder(order,b){return `🛒 NEUE BESTELLUNG · LUCA WEBSHOP\n\n🔢 Bestellnummer: ${order.orderNumber}\n🧾 Rechnung: ${order.invoiceNumber}\n📅 Datum: ${order.createdAt}\n\n👤 KUNDE\nName: ${order.customer.name}\nE-Mail: ${order.customer.email}\nAnschrift: ${order.customer.address}\n\n📦 BESTELLUNG\n${order.items.map(x=>`${x.name} · ${x.qty} Stück · ${x.price.toFixed(2).replace('.',',')} € / Stück`).join('\n')}\n\n💶 Gesamt: ${order.total.toFixed(2).replace('.',',')} €\n💳 Zahlungsstatus: ${order.paymentStatus}\n\n💰 ZAHLUNGSADRESSEN\nBTC: ${wallets.BTC}\nSOL: ${wallets.SOL}\nBNB Smart Chain: ${wallets.BNB}\n\n📊 WALLET-BESTÄNDE BEIM BESTELLEINGANG\nBTC: ${b.BTC}\nSOL: ${b.SOL}\nBNB: ${b.BNB}\n\nℹ️ Zahlung wird erst nach Prüfung als BEZAHLT markiert.`}
async function handle(u){const m=u.message;if(!m)return;const chatId=String(m.chat.id);const text=(m.text||'').trim();if(text==='/id'){return send(chatId,`🆔 Diese Telegram-Chat-ID lautet: ${chatId}\n\nFür den Support als LUCA_TELEGRAM_ADMIN_CHAT_ID in Render hinterlegen.`)}if(text==='/start'||text==='/help'){return send(chatId,`🤖 Luca Webshop Bestellbot ist aktiv.\n\nBestellungen werden an den konfigurierten Luca-Support-Chat gesendet.\n\nBot: @${botUsername}\nChat-ID: ${isAdmin(chatId)?'✓ Support-Chat konfiguriert':'nicht als Support-Chat hinterlegt'}\n\nAdmin-Befehle:\n/paid BESTELLNUMMER – Zahlung als bezahlt markieren\n/unpaid BESTELLNUMMER – Zahlung als unbezahlt markieren\n/order BESTELLNUMMER – Bestellung anzeigen\n/id – diese Chat-ID anzeigen`)}if(!isAdmin(chatId))return;if(text.toLowerCase().startsWith('/paid ')){const id=text.split(/\s+/)[1];const o=orders.get(id);if(!o)return send(chatId,`Bestellung ${id||''} wurde in diesem Bot-Lauf nicht gefunden.`);o.paymentStatus='BEZAHLT';return send(chatId,`✅ Zahlung bestätigt\n\nBestellung: ${o.orderNumber}\nRechnung: ${o.invoiceNumber}\nStatus: BEZAHLT`)}if(text.toLowerCase().startsWith('/unpaid ')){const id=text.split(/\s+/)[1];const o=orders.get(id);if(!o)return send(chatId,`Bestellung ${id||''} wurde in diesem Bot-Lauf nicht gefunden.`);o.paymentStatus='UNBEZAHLT';return send(chatId,`↩️ Zahlungsstatus zurückgesetzt\n\nBestellung: ${o.orderNumber}\nRechnung: ${o.invoiceNumber}\nStatus: UNBEZAHLT`)}if(text.toLowerCase().startsWith('/order ')){const id=text.split(/\s+/)[1];const o=orders.get(id);if(!o)return send(chatId,`Bestellung ${id||''} wurde in diesem Bot-Lauf nicht gefunden.`);return send(chatId,formatOrder(o,{BTC:'n/a',SOL:'n/a',BNB:'n/a'}))}}
async function loop(){if(!api)return;try{const updates=await tg('getUpdates',{offset,timeout:20,allowed_updates:['message']});for(const u of updates){offset=u.update_id+1;try{await handle(u)}catch(e){console.error('Telegram handler:',e.message)}}}catch(e){console.error('Telegram bot error:',e.message);await new Promise(r=>setTimeout(r,3000))}setTimeout(loop,500)}
async function init(){if(!api){console.log('Luca Telegram bot disabled: LUCA_TELEGRAM_BOT_TOKEN is not configured.');return}if(started)return;started=true;try{const me=await tg('getMe');console.log(`Luca Telegram bot authenticated as @${me.username||botUsername} (id ${me.id})`);await tg('deleteWebhook',{drop_pending_updates:false});console.log('Luca Telegram webhook cleared; polling enabled.');loop()}catch(e){started=false;console.error('Luca Telegram bot startup error:',e.message);setTimeout(init,5000)}}
async function sendOrder(order){if(!api)throw new Error('LUCA_TELEGRAM_BOT_TOKEN ist nicht konfiguriert.');if(!adminChatId)throw new Error('LUCA_TELEGRAM_ADMIN_CHAT_ID ist nicht konfiguriert. Bitte im Luca-Support-Chat /id senden und die ID in Render hinterlegen.');orders.set(order.orderNumber,order);const b=await getBalances();return send(adminChatId,formatOrder(order,b))}
init();
module.exports={enabled:!!api,sendOrder,getAdminChatId:()=>adminChatId,username:botUsername};
